class_name SkillTreeCatalog
extends RefCounted

# Positions are normalized graph coordinates consumed by the hangar skill-tree view.
# A node carrying a stage requirement remains visible as a milestone; its descendants
# are revealed only after that stage has been cleared.
const ORDER: Array[String] = [
	"core_damage",
	"distant_power",
	"anchored_power",
	"threat_uplink",
	"salvage_protocol",
	"impact_vector",
	"surrounded_power",
	"breach_rounds",
	"reinforced_core",
	"arc_conduction",
	"orbit_formation",
	"splash_payload",
	"reactive_shield",
	"arc_reach",
	"orbit_intercept",
	"volatile_radius",
	"emergency_cycle",
]

const DEFINITIONS := {
	"core_damage": {
		"name": "AMPLIFIED CORE",
		"description": "+4% all weapon damage.",
		"max_rank": 5,
		"costs": [40, 70, 110, 160, 220],
		"effect": "general_damage",
		"value": 0.04,
		"position": Vector2(0.50, 0.02),
	},
	"distant_power": {
		"name": "LONGSHOT ARRAY",
		"description": "+8% damage against distant enemies.",
		"max_rank": 3,
		"costs": [90, 140, 210],
		"effect": "distant_damage",
		"value": 0.08,
		"position": Vector2(0.08, 0.22),
		"requires": {"core_damage": 2},
	},
	"anchored_power": {
		"name": "SIEGE POSTURE",
		"description": "+7% damage after holding still for 2 seconds.",
		"max_rank": 3,
		"costs": [90, 140, 210],
		"effect": "stationary_damage",
		"value": 0.07,
		"position": Vector2(0.36, 0.22),
		"requires": {"core_damage": 2},
	},
	"threat_uplink": {
		"name": "THREAT UPLINK",
		"description": "Ranged Threats targeting reaches 55 px farther.",
		"max_rank": 3,
		"costs": [100, 155, 230],
		"effect": "ranged_target_reach",
		"value": 55.0,
		"position": Vector2(0.64, 0.22),
		"requires": {"core_damage": 2},
	},
	"salvage_protocol": {
		"name": "SALVAGE PROTOCOL",
		"description": "+6% enemy Flux and repair chance.",
		"max_rank": 3,
		"costs": [100, 160, 240],
		"effect": "fortune",
		"value": 0.06,
		"position": Vector2(0.92, 0.22),
		"requires": {"core_damage": 2},
	},
	"impact_vector": {
		"name": "IMPACT VECTOR",
		"description": "+32 weapon knockback.",
		"max_rank": 2,
		"costs": [180, 280],
		"effect": "knockback",
		"value": 32.0,
		"position": Vector2(0.08, 0.46),
		"requires": {"distant_power": 2},
		"mastery": {"pulse": 2},
	},
	"surrounded_power": {
		"name": "CLOSE QUARTERS",
		"description": "+9% damage while surrounded by at least 3 enemies.",
		"max_rank": 3,
		"costs": [180, 280, 410],
		"effect": "surrounded_damage",
		"value": 0.09,
		"position": Vector2(0.36, 0.46),
		"requires": {"anchored_power": 2},
	},
	"breach_rounds": {
		"name": "BREACH ROUNDS",
		"description": "Pulse rounds pierce one additional target.",
		"max_rank": 3,
		"costs": [190, 295, 430],
		"effect": "pulse_pierce",
		"value": 1.0,
		"position": Vector2(0.64, 0.46),
		"requires": {"threat_uplink": 2},
		"mastery": {"pulse": 2},
	},
	"reinforced_core": {
		"name": "REINFORCED CORE",
		"description": "+12 maximum hull.",
		"max_rank": 3,
		"costs": [190, 300, 440],
		"effect": "hull",
		"value": 12.0,
		"position": Vector2(0.92, 0.46),
		"requires": {"salvage_protocol": 2},
	},
	"arc_conduction": {
		"name": "ARC CONDUCTION",
		"description": "Arc Lash jumps to one additional target.",
		"max_rank": 3,
		"costs": [300, 440, 610],
		"effect": "arc_chain",
		"value": 1.0,
		"position": Vector2(0.08, 0.70),
		"requires": {"impact_vector": 1},
		"mastery": {"arc": 1},
	},
	"orbit_formation": {
		"name": "ORBIT FORMATION",
		"description": "Add one Orbit Blade to the formation.",
		"max_rank": 3,
		"costs": [300, 440, 610],
		"effect": "orbit_blade",
		"value": 1.0,
		"position": Vector2(0.36, 0.70),
		"requires": {"surrounded_power": 1},
		"mastery": {"orbit": 1},
	},
	"splash_payload": {
		"name": "SPLASH PAYLOAD",
		"description": "Pulse hits splash 16% damage to nearby enemies.",
		"max_rank": 3,
		"costs": [320, 470, 650],
		"effect": "splash_damage",
		"value": 0.16,
		"position": Vector2(0.64, 0.70),
		"requires": {"breach_rounds": 1},
	},
	"reactive_shield": {
		"name": "REACTIVE SHIELD",
		"description": "Gain one shield charge. Charges recover after avoiding damage.",
		"max_rank": 2,
		"costs": [340, 540],
		"effect": "shield",
		"value": 1.0,
		"position": Vector2(0.92, 0.70),
		"requires": {"reinforced_core": 1},
	},
	"arc_reach": {
		"name": "CONDUCTION REACH",
		"description": "Arc Lash jumps can reach 45 px farther.",
		"max_rank": 3,
		"costs": [480, 680, 920],
		"effect": "arc_reach",
		"value": 45.0,
		"position": Vector2(0.08, 0.94),
		"requires": {"arc_conduction": 1},
	},
	"orbit_intercept": {
		"name": "INTERCEPT LATTICE",
		"description": "Orbit Blades erase hostile projectiles within 14 px.",
		"max_rank": 3,
		"costs": [470, 670, 900],
		"effect": "orbit_intercept",
		"value": 14.0,
		"position": Vector2(0.36, 0.94),
		"requires": {"orbit_formation": 1},
	},
	"volatile_radius": {
		"name": "VOLATILE RADIUS",
		"description": "+22% Pulse splash radius.",
		"max_rank": 3,
		"costs": [500, 710, 960],
		"effect": "splash_radius",
		"value": 0.22,
		"position": Vector2(0.64, 0.94),
		"requires": {"splash_payload": 1},
	},
	"emergency_cycle": {
		"name": "EMERGENCY CYCLE",
		"description": "+8% active-skill recharge speed.",
		"max_rank": 3,
		"costs": [500, 720, 980],
		"effect": "ability_cooldown",
		"value": 0.08,
		"position": Vector2(0.92, 0.94),
		"requires": {"reactive_shield": 1},
	},
}


static func definition(id: String) -> Dictionary:
	return DEFINITIONS.get(id, {})


static func cost_for_rank(id: String, current_rank: int) -> int:
	var definition := definition(id)
	var costs: Array = definition.get("costs", [])
	if current_rank < 0 or current_rank >= costs.size():
		return 0
	return int(costs[current_rank])
