class_name SkillTreeCatalog
extends RefCounted

# Positions are normalized graph coordinates consumed by the hangar skill-tree view.
# A node carrying a stage requirement remains visible as a milestone; its descendants
# are revealed only after that stage has been cleared.
const ORDER: Array[String] = [
	"core_damage",
	"distant_power",
	"anchored_power",
	"pulse_acceleration",
	"salvage_protocol",
	"impact_vector",
	"surrounded_power",
	"projectile_matrix",
	"reinforced_core",
	"arc_overload",
	"orbit_overdrive",
	"splash_payload",
	"reactive_shield",
	"nova_reactor",
	"siege_posture_2",
	"volatile_radius",
	"emergency_cycle",
]

const DEFINITIONS := {
	"core_damage": {
		"name": "AMPLIFIED CORE",
		"description": "+4% all weapon damage per rank.",
		"max_rank": 5,
		"costs": [40, 70, 110, 160, 220],
		"effect": "general_damage",
		"value": 0.04,
		"position": Vector2(0.50, 0.02),
	},
	"distant_power": {
		"name": "LONGSHOT ARRAY",
		"description": "+8% damage beyond 280 px per rank.",
		"max_rank": 3,
		"costs": [90, 140, 210],
		"effect": "distant_damage",
		"value": 0.08,
		"position": Vector2(0.08, 0.22),
		"requires": {"core_damage": 2},
	},
	"anchored_power": {
		"name": "SIEGE POSTURE",
		"description": "+7% damage after holding still for 2 seconds per rank.",
		"max_rank": 3,
		"costs": [90, 140, 210],
		"effect": "stationary_damage",
		"value": 0.07,
		"position": Vector2(0.36, 0.22),
		"requires": {"core_damage": 2},
	},
	"pulse_acceleration": {
		"name": "PULSE ACCELERATOR",
		"description": "+10% Pulse Cannon projectile speed per rank.",
		"max_rank": 3,
		"costs": [100, 155, 230],
		"effect": "projectile_speed",
		"value": 0.10,
		"position": Vector2(0.64, 0.22),
		"requires": {"core_damage": 2},
	},
	"salvage_protocol": {
		"name": "SALVAGE PROTOCOL",
		"description": "+6% enemy Flux and repair chance per rank.",
		"max_rank": 3,
		"costs": [100, 160, 240],
		"effect": "fortune",
		"value": 0.06,
		"position": Vector2(0.92, 0.22),
		"requires": {"core_damage": 2},
	},
	"impact_vector": {
		"name": "IMPACT VECTOR",
		"description": "Weapon hits add 32 knockback per rank.",
		"max_rank": 2,
		"costs": [180, 280],
		"effect": "knockback",
		"value": 32.0,
		"position": Vector2(0.08, 0.46),
		"requires": {"distant_power": 2},
		"mastery": {"pulse": 2},
		"stage": "stage_1",
	},
	"surrounded_power": {
		"name": "CLOSE QUARTERS",
		"description": "+9% damage per rank while at least 3 enemies are within 220 px.",
		"max_rank": 3,
		"costs": [180, 280, 410],
		"effect": "surrounded_damage",
		"value": 0.09,
		"position": Vector2(0.36, 0.46),
		"requires": {"anchored_power": 2},
		"stage": "stage_1",
	},
	"projectile_matrix": {
		"name": "PROJECTILE MATRIX",
		"description": "+18% Pulse Cannon projectile size per rank.",
		"max_rank": 3,
		"costs": [190, 295, 430],
		"effect": "projectile_size",
		"value": 0.18,
		"position": Vector2(0.64, 0.46),
		"requires": {"pulse_acceleration": 2},
		"stage": "stage_1",
	},
	"reinforced_core": {
		"name": "REINFORCED CORE",
		"description": "+12 maximum hull per rank.",
		"max_rank": 3,
		"costs": [190, 300, 440],
		"effect": "hull",
		"value": 12.0,
		"position": Vector2(0.92, 0.46),
		"requires": {"salvage_protocol": 2},
		"stage": "stage_1",
	},
	"arc_overload": {
		"name": "IMPACT VECTOR II",
		"description": "Weapon hits add another 44 knockback per rank.",
		"max_rank": 3,
		"costs": [300, 440, 610],
		"effect": "knockback",
		"value": 44.0,
		"position": Vector2(0.08, 0.70),
		"requires": {"impact_vector": 1},
		"stage": "stage_2",
	},
	"orbit_overdrive": {
		"name": "ORBIT OVERDRIVE",
		"description": "+12% Orbit Blade damage per rank.",
		"max_rank": 3,
		"costs": [300, 440, 610],
		"effect": "orbit_damage",
		"value": 0.12,
		"position": Vector2(0.36, 0.70),
		"requires": {"surrounded_power": 1},
		"mastery": {"orbit": 1},
		"stage": "stage_2",
	},
	"splash_payload": {
		"name": "SPLASH PAYLOAD",
		"description": "Pulse hits deal 16% damage per rank to nearby enemies.",
		"max_rank": 3,
		"costs": [320, 470, 650],
		"effect": "splash_damage",
		"value": 0.16,
		"position": Vector2(0.64, 0.70),
		"requires": {"projectile_matrix": 1},
		"stage": "stage_2",
	},
	"reactive_shield": {
		"name": "REACTIVE SHIELD",
		"description": "Adds one shield charge per rank; charges recover after avoiding damage.",
		"max_rank": 2,
		"costs": [340, 540],
		"effect": "shield",
		"value": 1.0,
		"position": Vector2(0.92, 0.70),
		"requires": {"reinforced_core": 1},
		"stage": "stage_2",
	},
	"nova_reactor": {
		"name": "AMPLIFIED CORE II",
		"description": "+6% all weapon damage per rank.",
		"max_rank": 3,
		"costs": [480, 680, 920],
		"effect": "general_damage",
		"value": 0.06,
		"position": Vector2(0.08, 0.94),
		"requires": {"arc_overload": 1},
		"stage": "stage_3",
	},
	"siege_posture_2": {
		"name": "SIEGE POSTURE II",
		"description": "+10% damage after holding still for 2 seconds per rank.",
		"max_rank": 3,
		"costs": [470, 670, 900],
		"effect": "stationary_damage",
		"value": 0.10,
		"position": Vector2(0.36, 0.94),
		"requires": {"orbit_overdrive": 1},
		"stage": "stage_3",
	},
	"volatile_radius": {
		"name": "VOLATILE RADIUS",
		"description": "+22% Pulse splash radius per rank.",
		"max_rank": 3,
		"costs": [500, 710, 960],
		"effect": "splash_radius",
		"value": 0.22,
		"position": Vector2(0.64, 0.94),
		"requires": {"splash_payload": 1},
		"stage": "stage_3",
	},
	"emergency_cycle": {
		"name": "EMERGENCY CYCLE",
		"description": "+8% active-skill recharge speed per rank.",
		"max_rank": 3,
		"costs": [500, 720, 980],
		"effect": "ability_cooldown",
		"value": 0.08,
		"position": Vector2(0.92, 0.94),
		"requires": {"reactive_shield": 1},
		"stage": "stage_3",
	},
}


static func definition(id: String) -> Dictionary:
	return DEFINITIONS.get(id, {})


static func cost_for_rank(id: String, current_rank: int) -> int:
	var definition := definition(id)
	var costs: Array = definition.get("costs", [])
	if current_rank < 0 or current_rank >= costs.size():
		return 0
	return int(costs[current_rank])
